[package]
name = "localestring-merger"
version = "0.1.0"
authors = ["Quorin <xquoris@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.23"
dialoguer = "0.7.1"